"""empty message

Revision ID: 22ff0b3a88fc
Revises: 2d7ac93ee29e
Create Date: 2019-06-14 22:26:49.045786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ff0b3a88fc'
down_revision = '2d7ac93ee29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_author'), 'collection', ['author'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=10000), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_author'), 'post', ['author'], unique=False)
    op.create_table('collection_to_post',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'post_id')
    )
    op.create_index(op.f('ix_collection_to_post_collection_id'), 'collection_to_post', ['collection_id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('post', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_author'), 'comment', ['author'], unique=False)
    op.create_table('like_to_post',
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_index(op.f('ix_like_to_post_user_id'), 'like_to_post', ['user_id'], unique=False)
    op.create_table('like_to_comment',
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    op.create_index(op.f('ix_like_to_comment_user_id'), 'like_to_comment', ['user_id'], unique=False)
    op.add_column('user', sa.Column('karma', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'karma')
    op.drop_index(op.f('ix_like_to_comment_user_id'), table_name='like_to_comment')
    op.drop_table('like_to_comment')
    op.drop_index(op.f('ix_like_to_post_user_id'), table_name='like_to_post')
    op.drop_table('like_to_post')
    op.drop_index(op.f('ix_comment_author'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_collection_to_post_collection_id'), table_name='collection_to_post')
    op.drop_table('collection_to_post')
    op.drop_index(op.f('ix_post_author'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_collection_author'), table_name='collection')
    op.drop_table('collection')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
