"""empty message

Revision ID: 2bfb41beafe5
Revises: 8efa1ef1a1e2
Create Date: 2019-06-15 15:56:38.450939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfb41beafe5'
down_revision = '8efa1ef1a1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_username', sa.String(), nullable=False))
    op.create_index(op.f('ix_comment_author_username'), 'comment', ['author_username'], unique=False)
    op.create_foreign_key(None, 'comment', 'user', ['author_username'], ['username'])
    op.add_column('post', sa.Column('author_username', sa.String(), nullable=False))
    op.create_index(op.f('ix_post_author_username'), 'post', ['author_username'], unique=False)
    op.create_foreign_key(None, 'post', 'user', ['author_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_post_author_username'), table_name='post')
    op.drop_column('post', 'author_username')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_author_username'), table_name='comment')
    op.drop_column('comment', 'author_username')
    # ### end Alembic commands ###
